name: Deployment triggered tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-core-workflow:
    uses: ./.github/workflows/core-flow.yml
    secrets: inherit

