name: Manually triggered tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn clean test

      - name: Parse Test Results
        id: parse_results
        run: |
          TEST_RESULT_FILE=$(ls target/surefire-reports/TEST-*.xml | head -n 1)
          TOTAL_TESTS=$(xmllint --xpath 'string(/testsuite/@tests)' $TEST_RESULT_FILE)
          FAILURES=$(xmllint --xpath 'string(/testsuite/@failures)' $TEST_RESULT_FILE)
          SKIPPED=$(xmllint --xpath 'string(/testsuite/@skipped)' $TEST_RESULT_FILE)
          ERRORS=$(xmllint --xpath 'string(/testsuite/@errors)' $TEST_RESULT_FILE)
          PASSED=$((TOTAL_TESTS - FAILURES - SKIPPED - ERRORS))
          DURATION=$(xmllint --xpath 'string(/testsuite/@time)' $TEST_RESULT_FILE)
          echo "total=$TOTAL_TESTS" >> $GITHUB_ENV
          echo "passed=$PASSED" >> $GITHUB_ENV
          echo "failures=$FAILURES" >> $GITHUB_ENV
          echo "skipped=$SKIPPED" >> $GITHUB_ENV
          echo "errors=$ERRORS" >> $GITHUB_ENV
          echo "duration=$DURATION" >> $GITHUB_ENV

      - name: Load test report history
        uses: actions/checkout@v4.1.4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
          keep_reports: 20

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Post to a Slack channel
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07222GE4RY'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Selenium Synthetic Tests Results*"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Results:*       ${{ env.passed }}/ ${{ env.total }} Passed ( $((100 * env.passed / env.total))% )"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Duration:*    ${{ env.duration }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://your-test-report-url|Go to Test Results>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://your-github-action-url|Go to Github Action>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
